services:
  app:
    build: .
    env_file: .env
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
    volumes:
      - .:/app:delegated
    command: python main.py
    depends_on:
      - localhost

  db:
    image: postgres:14
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5433"

  streamlit:
    build: .
    ports:
      - "8501:8501"
    env_file: .env
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
    volumes:
      - .:/app:delegated
    command: streamlit run app.py
    depends_on:
      - localhost

volumes:
  postgres_data: